dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: PORT=3001 bin/server
server-wait: 1
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: v1.apib
endpoint: 'http://localhost:3001'
